"""Application features/domain modules."""

# Feature modules are available for import
# from .documents import ...
# from .agents import ...
# from .chat import ...
# from .knowledge_base import ...
# from .health import ...
# from .web_scraping import ...

__all__ = [
    "documents",
    "agents",
    "chat",
    "knowledge_base",
    "health",
    "web_scraping",
]
