"""Search feature constants."""

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
DEFAULT_SEARCH_CACHE_TTL_SECONDS = 900
DEFAULT_RAG_TOKEN_BUDGET = 2_000
HYBRID_CANDIDATE_LIMIT = 50
RRF_K = 60
INGEST_CHUNK_SIZE = 512
INGEST_CHUNK_OVERLAP = 64
INGEST_EMBEDDING_BATCH_SIZE = 200
ANALYZE_THRESHOLD_CHUNKS = 10_000
DISKANN_QUERY_SEARCH_LIST_SIZE = 100
DISKANN_QUERY_RESCORE = 50
SEARCH_CHUNKS_BM25_INDEX_NAME = "search_chunks_bm25_idx"
