"""Create the five relations the phantom revisions never created.

Revision ID: 0014
Revises: 0013
Create Date: 2026-08-23 01:40:00.000000

Why this revision exists
------------------------
The deployed database was **stamped, not migrated**: ``alembic_version`` was set
to ``0009`` without ``0009``'s ancestors having executed. Five of the eight
revisions that stamp marks applied left no relations behind, and because they
are recorded as applied they will **never execute again**:

======================  ===============================================
revision                relations it should have created
======================  ===============================================
``0006``        ``chat_sessions``, ``chat_messages``,
                        ``document_vectors``
``0009``        ``search_documents``, ``search_chunks``
``0007``        (a column rename that never happened)
``0010``        ``parent_documents``, ``clauses``
``0006``                ``outbox_events``, ``dead_letter_events``
======================  ===============================================

``0006``'s two relations were repaired by ``0013``. This revision
repairs the five from ``0006`` and ``0009``. ``0010``'s
two are deliberately **not** repaired here: ``parent_documents`` and ``clauses``
were removed from the ORM registry by this same change as dead trees, so
creating them would reintroduce relations nothing maps.

The measured symptom this closes: with these five absent, ``alembic check``
proposed ``add_table`` for every one of them. Autogenerate proposing to CREATE a
relation is the benign direction — the dangerous direction is a relation absent
from ``Base.metadata``, which autogenerate proposes to **DROP**. Neither
direction should be left standing, because a future ``--autogenerate`` would
fold these five into an unrelated revision.

Shape is taken from the ORM, not from the revisions that failed to run
---------------------------------------------------------------------
Every statement below was generated by compiling ``CreateTable`` /
``CreateIndex`` against the live ``Base.metadata`` under the PostgreSQL dialect,
then transcribed with ``IF NOT EXISTS`` added. It is deliberately **literal DDL
rather than a runtime** ``metadata.create_all`` **call**: a revision that reads
``Base.metadata`` when it executes creates whatever the models happen to say at
*run* time, so its meaning changes as the models drift. A revision must be a
fixed point in history. Compiling the DDL at authoring time gets the exactness
of the ORM without the non-determinism of consulting it later.

Consequences of taking the shape from the ORM rather than from the dead
revisions, both intentional:

- ``document_vectors`` gets a column named ``metadata``, **not** ``meta_data``.
  ``0007`` ("rename_metadata_to_meta_data") is one of the phantoms; it
  never ran, and the ORM still declares ``metadata``. The ORM is what
  ``alembic check`` compares against, so matching the ORM is what makes the
  drift close.
- ``search_chunks`` gets **no** index. The ORM declares none, and
  ``features/search/constants.py:15`` pins
  ``SEARCH_CHUNKS_BM25_INDEX_NAME = "search_chunks_bm25_idx"`` with **zero
  readers**. Creating an index the ORM does not declare would trade an
  ``add_table`` for a permanent ``remove_index`` — swapping one drift for
  another. The unindexed ``embedding`` column is real technical debt, and it is
  recorded as such rather than silently patched here: the retrieval path this
  change consolidates onto is ``chunks``, whose three index branches
  ``0013`` creates under their contract names.

The enum needs a guard that ``IF NOT EXISTS`` cannot give it
------------------------------------------------------------
``chat_messages.role`` is a **native** enum (``native_enum=True``), so the type
``message_role`` must exist before the table. PostgreSQL has no
``CREATE TYPE IF NOT EXISTS``, so the idempotence of this revision cannot be
expressed the way every other statement here expresses it. The ``DO`` block
below catches ``duplicate_object`` instead, which is the standard substitute and
the only one that keeps the whole revision re-runnable.

``content_tsv`` is generated, and its immutability is load-bearing
------------------------------------------------------------------
``search_chunks.content_tsv`` is ``GENERATED ALWAYS AS
(to_tsvector('english', content)) STORED``. This works only because the
**two-argument** ``to_tsvector(regconfig, text)`` is ``IMMUTABLE``. The
one-argument ``to_tsvector(text)`` is merely ``STABLE`` — it reads
``default_text_search_config`` — and PostgreSQL rejects a ``STABLE`` function in
a generated column. The explicit ``'english'`` argument is therefore not a
stylistic choice; dropping it makes the column definition invalid.

Ordering
--------
``search_documents`` precedes ``search_chunks``, which carries
``fk_search_chunks_document_id_search_documents``. The three
``0006`` relations have no foreign keys and no ordering constraint
among them.

Reversal
--------
``downgrade()`` is an intentional no-op, consistent with ``0012`` and
``0013``. Reversal below that merge is unsupported, and dropping these
relations would restore precisely the drift this revision closes while leaving
``0006`` and ``0009`` still recorded as having created them.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0014"
down_revision: str | Sequence[str] | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 0. The native enum chat_messages.role depends on. No IF NOT EXISTS
    #    form exists for CREATE TYPE, so catch duplicate_object instead.
    # ------------------------------------------------------------------
    op.execute("""
        DO $$
        BEGIN
            CREATE TYPE message_role AS ENUM ('user', 'assistant', 'system');
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$
    """)

    # ------------------------------------------------------------------
    # 1. 0006's relations: chat + document_vectors.
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS chat_sessions (
            id             SERIAL                   NOT NULL,
            session_id     VARCHAR(100)             NOT NULL,
            user_id        VARCHAR(100)             NOT NULL,
            title          VARCHAR(500),
            extra_metadata JSON,
            created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
            updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT pk_chat_sessions PRIMARY KEY (id)
        )
    """)
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS ix_chat_sessions_session_id "
        "ON chat_sessions (session_id)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_chat_sessions_user_id ON chat_sessions (user_id)")

    op.execute("""
        CREATE TABLE IF NOT EXISTS chat_messages (
            id             SERIAL                   NOT NULL,
            session_id     VARCHAR(100)             NOT NULL,
            user_id        VARCHAR(100)             NOT NULL,
            role           message_role             NOT NULL,
            content        TEXT                     NOT NULL,
            model          VARCHAR(100),
            tokens_used    INTEGER,
            extra_metadata JSON,
            created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT pk_chat_messages PRIMARY KEY (id)
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_chat_messages_session_id ON chat_messages (session_id)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_chat_messages_user_id ON chat_messages (user_id)")

    # The column is named ``metadata`` because 0002's rename is a
    # phantom — see the docstring. This matches the ORM, which is the
    # comparand ``alembic check`` uses.
    op.execute("""
        CREATE TABLE IF NOT EXISTS document_vectors (
            id          SERIAL                   NOT NULL,
            user_id     VARCHAR(100)             NOT NULL,
            document_id VARCHAR(100)             NOT NULL,
            title       VARCHAR(500)             NOT NULL,
            content     TEXT                     NOT NULL,
            vector_id   VARCHAR(100),
            metadata    JSON,
            created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
            updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT pk_document_vectors PRIMARY KEY (id)
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_document_vectors_document_id "
        "ON document_vectors (document_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_document_vectors_user_id ON document_vectors (user_id)"
    )

    # ------------------------------------------------------------------
    # 2. 0009's relations. search_documents first — search_chunks
    #    carries the foreign key onto it.
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS search_documents (
            id           UUID                     NOT NULL,
            source_uri   TEXT,
            title        VARCHAR(500)             NOT NULL,
            content_hash VARCHAR(64)              NOT NULL,
            doc_metadata JSONB                    NOT NULL,
            ingested_at  TIMESTAMP WITH TIME ZONE NOT NULL,
            updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT pk_search_documents PRIMARY KEY (id),
            CONSTRAINT uq_search_documents_content_hash UNIQUE (content_hash)
        )
    """)

    # content_tsv uses the TWO-argument to_tsvector deliberately: only that
    # overload is IMMUTABLE, and a generated column rejects STABLE.
    op.execute("""
        CREATE TABLE IF NOT EXISTS search_chunks (
            id             UUID                     NOT NULL,
            document_id    UUID                     NOT NULL,
            chunk_index    INTEGER                  NOT NULL,
            content        TEXT                     NOT NULL,
            embedding      VECTOR(768),
            chunk_metadata JSONB                    NOT NULL,
            content_tsv    TSVECTOR                 GENERATED ALWAYS AS (
                                                        to_tsvector('english', content)
                                                    ) STORED NOT NULL,
            created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
            updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT pk_search_chunks PRIMARY KEY (id),
            CONSTRAINT uq_search_chunks_document_chunk_index UNIQUE (document_id, chunk_index),
            CONSTRAINT fk_search_chunks_document_id_search_documents
                FOREIGN KEY (document_id) REFERENCES search_documents (id) ON DELETE CASCADE
        )
    """)


def downgrade() -> None:
    """Intentional no-op — see the module docstring's Reversal section."""
