from enum import StrEnum


class McpErrorCode(StrEnum):
    MCP_UPSTREAM_NOT_CONFIGURED = "MCP_UPSTREAM_NOT_CONFIGURED"
    MCP_UPSTREAM_INVALID_CONFIG = "MCP_UPSTREAM_INVALID_CONFIG"
    MCP_UPSTREAM_CIRCUIT_OPEN = "MCP_UPSTREAM_CIRCUIT_OPEN"
    MCP_UPSTREAM_TOOL_NOT_ALLOWED = "MCP_UPSTREAM_TOOL_NOT_ALLOWED"
