"""Utility modules for the application."""

# Keep shared.result below logger exports to avoid package-init recursion.
# ruff: noqa: I001

from .logger import (
    execution_path,
    logger,
    request_state,
    set_request_actor,
    setup_logging,
    trace_layer,
)
from .api_features import APIFeatures
from .exceptions import (
    APIException,
    ConflictException,
    DatabaseException,
    ExternalServiceException,
    ForbiddenException,
    InfrastructureException,
    NotFoundException,
    ServiceUnavailableException,
    TooManyRequestsException,
    UnauthorizedException,
    ValidationException,
)
from .cache import (
    RedisGuardAdapter,
    add_to_bloom_filter,
    check_bloom_filter,
    create_bloom_filter,
    create_search_index,
    delete_cache,
    delete_hash,
    delete_hash_field,
    delete_list,
    delete_search_index,
    deserialize_data,
    execute_pipeline,
    get_bloom_filter_info,
    get_cache,
    get_cache_key,
    get_hash,
    get_key_name,
    get_list_items,
    get_list_length,
    push_to_list,
    remove_from_list,
    search_index,
    serialize_data,
    set_cache,
    set_hash,
    trim_list,
    update_hash,
    update_list_item,
)
from .codes import Environment, ErrorCode
from .embedding import normalize_embedding
from .json_serializer import (
    from_json,
    from_json_float_list,
    to_float_list_bytes,
    to_float_list_str,
    to_json_bytes,
    to_json_str,
    to_sorted_key_bytes,
)
from app.shared.result import (
    APIResponse,
    DependencyHealth,
    ErrorDetail,
    HealthResponse,
    HealthStatus,
    RequestMeta,
    http_error,
    http_response,
)

__all__ = [  # noqa: RUF022
    "APIException",
    "APIFeatures",
    "APIResponse",
    "ConflictException",
    "DatabaseException",
    "DependencyHealth",
    "Environment",
    "ErrorCode",
    "ErrorDetail",
    "ExternalServiceException",
    "ForbiddenException",
    "InfrastructureException",
    "NotFoundException",
    "RedisGuardAdapter",
    "RequestMeta",
    "ServiceUnavailableException",
    "TooManyRequestsException",
    "UnauthorizedException",
    "ValidationException",
    "HealthResponse",
    "HealthStatus",
    "execution_path",
    "from_json",
    "from_json_float_list",
    "http_error",
    "http_response",
    "logger",
    "normalize_embedding",
    "request_state",
    "set_request_actor",
    "setup_logging",
    "to_float_list_bytes",
    "to_float_list_str",
    "to_json_bytes",
    "to_json_str",
    "to_sorted_key_bytes",
    "trace_layer",
]
