"""RAG (Retrieval-Augmented Generation) utilities."""

from app.shared.rag.langextract import (
    LangExtractBatchConfig,
    LangExtractConfig,
    abatch_extract_langextract,
    aextract_langextract,
)
from app.shared.rag.pageindex import (
    PageIndexBatchConfig,
    PageIndexChatConfig,
    PageIndexConfig,
    abatch_page_index,
    achat_completion,
    apage_index,
    astream_chat_completions,
    create_node_map,
    gather_node_text,
)
from app.shared.rag.strategies import (
    AgenticRAGResult,
    LateChunk,
    QueryExpansionResult,
    RAGStrategyService,
    RetrievedDocument,
    cosine_similarity,
    deduplicate_strings,
    deserialize_metadata,
    format_graph_results,
    format_retrieved_documents,
    late_chunk_text,
    mean_pool_embeddings,
    parse_query_variants,
    prepare_training_data,
    semantic_chunk_text,
    serialize_metadata,
    split_text,
)

__all__ = [
    "AgenticRAGResult",
    "LangExtractBatchConfig",
    "LangExtractConfig",
    "LateChunk",
    "PageIndexBatchConfig",
    "PageIndexChatConfig",
    "PageIndexConfig",
    "QueryExpansionResult",
    "RAGStrategyService",
    "RetrievedDocument",
    "abatch_extract_langextract",
    "abatch_page_index",
    "achat_completion",
    "aextract_langextract",
    "apage_index",
    "astream_chat_completions",
    "cosine_similarity",
    "create_node_map",
    "deduplicate_strings",
    "deserialize_metadata",
    "format_graph_results",
    "format_retrieved_documents",
    "gather_node_text",
    "late_chunk_text",
    "mean_pool_embeddings",
    "parse_query_variants",
    "prepare_training_data",
    "semantic_chunk_text",
    "serialize_metadata",
    "split_text",
]
